"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.annotate = exports.html2ogxt = exports.cleanupAnnotations = exports.cleanupHtml = exports.parseTitle = void 0;
var parseTitle_1 = require("./parseTitle");
Object.defineProperty(exports, "parseTitle", { enumerable: true, get: function () { return parseTitle_1.parseTitle; } });
var cleanup_1 = require("./cleanup");
Object.defineProperty(exports, "cleanupHtml", { enumerable: true, get: function () { return cleanup_1.cleanupHtml; } });
Object.defineProperty(exports, "cleanupAnnotations", { enumerable: true, get: function () { return cleanup_1.cleanupAnnotations; } });
var html2ogxt_1 = require("./html2ogxt");
Object.defineProperty(exports, "html2ogxt", { enumerable: true, get: function () { return html2ogxt_1.html2ogxt; } });
var annotate_1 = require("./annotate");
Object.defineProperty(exports, "annotate", { enumerable: true, get: function () { return annotate_1.annotate; } });
